# HP-UX Ripl General Makefile
# Ripl Version 1.1
# Written by Richard A. Cook, 17/5/98.
#
# Install script moves this into Ripl directory.
# This builds all libraries and executables.

CFLAGS = -Aa -Ioplib -Iriplmain -Iriplop -Iripltool
LIBS = oplib.a riplmain.a riplop.a ripltool.a
DIRS = ${LIBS:.a=} examples
PROG = ripl
all:
	for i in ${DIRS}; do cd $$i; ${MAKE} all; cd ..; done
	${CC} ${CFLAGS} ${LDFLAGS} \
		riplcmd/riplcmd.c \
		riplop.a \
		oplib.a \
		riplmain.a \
		ripltool.a \
		-oripl -lm
depend:
	for i in ${DIRS}; do cd $$i; ${MAKE} depend; cd ..; done
clean:
	for i in ${DIRS}; do cd $$i; ${MAKE} clean; cd ..; done
	rm -f core Makefile.bak *.o *.a ripl
update:
	for i in ${DIRS}; do cd $$i; ${MAKE} update; cd ..; done
