# HP-UX Ripl Examples Makefile
# Ripl Version 1.1
# Written by Richard A. Cook, 17/5/98.
#
# Install script moves this into 'examples' subdirectory.
# This builds all the examples executables.

SRCS = \
	haar1.c \
	haar2.c \
	hist.c \
	matrix.c \
	noise.c \
	sine.c \
	wavelet.c \
	wavelet2.c \
	wavelet3.c \
	wavelet4.c \
	wavelet5.c \
	wavelet6.c \
	wavelet7.c \
	wavelet8.c
PROGS = ${SRCS:.c=}

CFLAGS = -Aa -I../riplmain -I../ripltool
# For some reason we have to link ../riplmain.a last.
LIBS = ../oplib.a ../riplop.a ../ripltool.a ../riplmain.a

all: ${PROGS}
.c:
	${CC} ${CFLAGS} ${LDFLAGS} $< ${LIBS} -o$@ -lm
depend:
	makedepend -- ${CFLAGS} -- ${SRCS}
clean:
	rm -f core Makefile.bak ${OBJS}
cleanall:
	rm -f core Makefile.bak ${OBJS} ${PROGS}
update:
